# Generated by Django 5.1.4 on 2024-12-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view a book'), ('can_create', 'can create a book'), ('can_edit', 'can edit a book'), ('can_delete', 'can delete a book')]},
        ),
    ]
